Picture tag Support
unstackinc/delta-py pull request #15
Opened 2021-02-11 05:08 UTC by FarhanShoukat

2021-02-11 05:11 UTC, FarhanShoukat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Image optimization 2.0](https://trello.com/c/ytve55Hk/924-image-optimization-20)

2021-02-16 14:40 UTC, stevenmoseley requested changes

2021-02-16 14:40 UTC, stevenmoseley commented on delta/html.py
> +    return base_picture(root, op)
`base_picture()` isn't reall necessary if it's only called here. Why not just have all the code in `picture()`?

2021-02-16 14:41 UTC, stevenmoseley requested changes

2021-02-16 14:41 UTC, stevenmoseley commented on delta/html.py
> +            a.attrib['rel'] = 'noopener noreferrer'
Isn't a lot of this code reused from the `base_image` function? Is there a simple way to have a shared set of functions that they can both use?

2021-02-17 06:00 UTC, FarhanShoukat commented
@stevenmoseley made requested changes.

2021-02-23 14:33 UTC, stevenmoseley approved these changes

2021-02-23 14:33 UTC, merged